import os
import re
import json
import shutil


import xml.etree.ElementTree as ET
import xml.dom.minidom as minidom

'''
This script creates wiki pages from documentation pages generated by docfx
From this repo's root directory, run:
dotnet docfx metadata docfx.json --outputFormat mref
to generate the files needed for this script.
'''

def convertToDocs(node, class_from, class_to, sep):
    node_class_name = node.attrib["name"]
    node_class_name = node_class_name[2:]

    wiki_section = []
    class_call = "== {0} ==".format(node_class_name[(len(class_from)+1):])
    wiki_section.append(class_call)

    if node.type == "F":
        param_names = []
        for param_node in node.iter('param'):
            param_names.append(param_node.attrib["name"])
        arg_signature = "({0})".format(", ".join(param_names))
    else:
        arg_signature = ""
    class_code = "<code>{0}{1}{2}{3}</code>".format(class_to, sep, node_class_name[(len(class_from)+1):], arg_signature)
    wiki_section.append(class_code)

    if node.type != "F":
        type_note = "'''Type:''' {0}".format(node.member_type)
        wiki_section.append(type_note)

    summary_node = node.find("summary")
    if summary_node is not None and summary_node.text is not None:
        summary_lines = summary_node.text.split("\n")
        summary_lines = [line.strip() for line in summary_lines]
        wiki_section.append("\n".join(summary_lines))

    params = []
    for param_node in node.iter('param'):
        params.append("{{ArgRow\n|name={0}\n|type={1}\n|desc={2}\n}}".format(param_node.attrib["name"], param_node.attrib["type"], param_node.text))

    if len(params) > 0:
        args_header = "==== Parameters ===="
        wiki_section.append(args_header)

        wiki_section.append("{| class=\"wikitable\"\n{{ArgHeader}}{0}|}".format("\n".join(params)))

    returns = ""
    returns_node = node.find("returns")
    if returns_node is not None and returns_node.text is not None:
        returns = "{{ReturnRow\n|type={0}\n|desc={1}\n}}".format(returns_node.attrib["type"], returns_node.text)

    if returns != "":
        returns_header = "==== Returns ===="
        wiki_section.append(returns_header)

        wiki_section.append("{| class=\"wikitable\"\n{{ReturnHeader}}{0}|}".format(returns))

    example_node = node.find("example")

    if example_node is not None:
        example_header = "==== Example ===="
        wiki_section.append(example_header)

        example_lines = example_node.text.split("\n")
        example_lines = [line.strip() for line in example_lines]
        example = "<pre>\n{0}\n</pre>".format("\n".join(example_lines))
        wiki_section.append(example)

    wiki_section.append("=== Usage ===")
    wiki_section.append("---")

    return "\n\n".join(wiki_section)

def getRelevantClassMap(node, classes, node_types):

    node_class_name = node.attrib["name"]
    node_separator = None
    for node_type in node_types:
        if node_class_name.startswith(node_type + ":"):
            node_separator = node_types[node_type]

    if node_separator is not None:
        node_class_name = node_class_name[2:]
        for class_name in classes:
            if node_class_name.startswith(class_name):
                return (class_name, node_separator)

    return None, None

def convertClassesToWiki(out_file, classes, node_types):
    doc_paths = ["RogueEssence.xml", "PMDC.xml", "RogueElements.xml"]

    with open(os.path.join("..", "DataAsset", "Docs", out_file + ".txt"), 'w', encoding='utf-8') as txt:
        txt.write("This page shows all properties of {0} that can be manipulated from Lua\n\n".format(out_file))
        for doc_path in doc_paths:
            tree = ET.parse(os.path.join("..","DumpAsset","Editor","Docs", doc_path))
            root = tree.getroot()
            members_node = root.find('members')
            for member_node in members_node.iter('member'):
                class_key, sep = getRelevantClassMap(member_node, classes, node_types)
                if class_key is not None:
                    doc_txt = convertToDocs(member_node, class_key, classes[class_key], sep)
                    txt.write(doc_txt + "\n\n")

        txt.write("[[Category:Data Class Documentation]]")

def main():

    os.makedirs(os.path.join("..", "DataAsset", "Docs", "Functions"), exist_ok=True)
    os.makedirs(os.path.join("..", "DataAsset", "Docs", "Class"), exist_ok=True)

    class_maps = {
        "RogueEssence.Script.ScriptAI": "AI"
    }
    convertClassesToWiki("Functions/AI", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptDungeon": "DUNGEON"
    }
    convertClassesToWiki("Functions/Dungeon", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptGame": "GAME",
    }
    convertClassesToWiki("Functions/Game", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptGround": "GROUND",
    }
    convertClassesToWiki("Functions/Ground", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptSound": "SOUND",
    }
    convertClassesToWiki("Functions/Sound", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptStrings": "STRINGS",
    }
    convertClassesToWiki("Functions/Strings", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptTask": "TASK",
    }
    convertClassesToWiki("Functions/Task", class_maps, {"M": ":", "F": ":"})

    class_maps = {
        "RogueEssence.Script.ScriptUI": "UI",
    }
    convertClassesToWiki("Functions/UI", class_maps, {"M": ":", "F": ":"})


    class_maps = {
        "RogueEssence.Dungeon.Character": "Character",
        "RogueEssence.Dungeon.CharData": "CharData"
    }
    convertClassesToWiki("Class/Character", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Ground.GroundChar": "GroundChar",
        "RogueEssence.Ground.GroundAIUser": "GroundAIUser",
        "RogueEssence.Ground.BaseTaskUser": "BaseTaskUser",
        "RogueEssence.Ground.GroundEntity": "GroundEntity"
    }
    convertClassesToWiki("Class/GroundChar", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Dungeon.BattleContext": "BattleContext",
        "RogueEssence.Dungeon.UserTargetGameContext": "UserTargetGameContext",
        "RogueEssence.Dungeon.GameContext": "GameContext"
    }
    convertClassesToWiki("Class/BattleContext", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.BattleData": "BattleData"
    }
    convertClassesToWiki("Class/BattleData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.TileData": "TileData"
    }
    convertClassesToWiki("Class/TileData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.MapStatusData": "MapStatusData"
    }
    convertClassesToWiki("Class/MapStatusData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.StatusData": "StatusData"
    }
    convertClassesToWiki("Class/StatusData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.SkillData": "SkillData"
    }
    convertClassesToWiki("Class/SkillData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.IntrinsicData": "IntrinsicData"
    }
    convertClassesToWiki("Class/IntrinsicData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.ItemData": "ItemData"
    }
    convertClassesToWiki("Class/ItemData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.MonsterData": "MonsterData",
        "RogueEssence.Data.BaseMonsterForm": "BaseMonsterForm",
        "PMDC.Data.MonsterFormData": "MonsterFormData"
    }
    convertClassesToWiki("Class/MonsterData", class_maps, {"P": ".", "F": "."})

    class_maps = {
        "RogueEssence.Data.DataManager": "_DATA"
    }
    convertClassesToWiki("Class/DataManager", class_maps, {"P": ".", "F": ".", "M": ":"})

    print("Complete.")

if __name__ == '__main__':
    main()