import os
import re
import json
import shutil
import yaml

import xml.etree.ElementTree as ET
import xml.dom.minidom as minidom

'''
This script creates wiki pages from documentation pages generated by docfx
From this repo's root directory, run:
dotnet docfx metadata docfx.json --outputFormat mref
to generate the files needed for this script.
'''

def convertToDocs(node, backup_node, friendly_name):
    attrib_name = node['source']['id']

    wiki_section = []
    table_section = []

    method_node = None
    if node['type'] == 'Method':
        method_node = node
    elif backup_node is not None and backup_node['type'] == 'Method':
        method_node = backup_node

    if method_node is not None:
        wiki_section.append("{{ClassMethod")
    else:
        wiki_section.append("{{ClassProperty")

    wiki_section.append("|title={0}".format(attrib_name))

    if method_node is not None:
        sep = ':'
        param_names = []
        if 'parameters' in method_node['syntax']:
            for param_node in method_node['syntax']['parameters']:
                param_names.append(param_node["id"])
        arg_signature = "({0})".format(", ".join(param_names))
    else:
        sep = '.'
        arg_signature = ""
    wiki_section.append("|call={0}{1}{2}{3}".format(friendly_name, sep, attrib_name, arg_signature))

    if method_node is None:
        member_type = node['syntax']['return']['type']
        wiki_section.append("|type={0}".format(member_type))

    description = ""
    if 'summary' in node:
        summary_node = node['summary']
        description = summary_node.replace('\n', '<br>')
        wiki_section.append("|description={0}".format(description))

    params = []
    if method_node is not None:
        table_section.append('<tr>\n<td>'+attrib_name+'</td>\n<td>'+description+'</td>\n</tr>')
        if 'parameters' in method_node['syntax']:
            for param_node in method_node['syntax']['parameters']:
                description = ""
                if 'description' in param_node:
                    description = param_node['description'].replace('\n', '<br>')
                params.append("{{ArgRow|name="+param_node["id"]+"|type="+param_node["type"]+"|desc="+description+"}}")

    if len(params) > 0:
        wiki_section.append("|params=")
        for param in params:
            wiki_section.append(param)

    returns = ""
    if method_node is not None:
        if 'return' in node['syntax']:
            returns_node = node['syntax']['return']
            description = ""
            if 'description' in returns_node:
                description = returns_node['description'].replace('\n', '<br>')
            returns = "{{ReturnRow|type="+returns_node["type"]+"|desc="+description+"}}"

    if returns != "":
        wiki_section.append("|returns=")
        wiki_section.append(returns)

    examples = []
    if 'example' in node:
        for example in node['example']:
            examples.append(example.replace('\n', '<br>'))
    if len(examples) > 0:
        wiki_section.append("|example=")
        wiki_section.append("<br><br>".join(examples))

    wiki_section.append("|notes=")

    wiki_section.append("}}")
    return "\n".join(wiki_section), "\n".join(table_section)

def convert_to_link(source_file):
    github_repo_map = {}
    github_repo_map[r'https://github.com/PMDCollab/PMDC/blob/master/PMDC'] = os.path.abspath(os.path.join('..', 'PMDC', 'PMDC'))
    github_repo_map[r'https://github.com/RogueCollab/RogueEssence/blob/master/RogueEssence'] = os.path.abspath(os.path.join('..', 'PMDC', 'RogueEssence', 'RogueEssence'))
    github_repo_map[r'https://github.com/audinowho/RogueElements/blob/master/RogueElements'] = os.path.abspath(os.path.join('..', 'PMDC', 'RogueEssence', 'RogueElements', 'RogueElements'))

    for link in github_repo_map:
        parent_path = github_repo_map[link]
        if source_file.startswith(parent_path):
            head = source_file[len(parent_path):]
            final_link = link + head.replace('\\', '/')
            return final_link
    return None

def convert_to_filename(main_out_file, source_file, split_format):
    if split_format is None:
        return main_out_file

    _, filename = os.path.split(source_file)
    base_name, _ = os.path.splitext(filename)
    truncated_name = base_name[len(split_format):]
    name_pieces = []
    last_start = 0
    for ii in range(1, len(truncated_name)):
        if truncated_name[ii].isupper():
            name_pieces.append(truncated_name[last_start:ii])
            last_start = ii
    name_pieces.append(truncated_name[last_start:])
    return main_out_file + "/" + "_".join(name_pieces)

def convertClassesToWiki(main_out_file, friendly_name, is_singleton, is_quick_reference, classes, split_format, accepted_types):

    ref_links = {}
    out_files = {}
    table_files = {}


    for class_name in classes:
        with open(os.path.join("..", "DataAsset", "Docs", class_name + ".yml"), 'r') as file:
            class_yaml = yaml.safe_load(file)

        item_links = {}
        skip_items = {}
        for item in class_yaml['items']:
            if item['type'] in accepted_types:
                if 'summary' in item:
                    summary_re = re.search(r'\[LuaFunction\] (\S+)', item['summary'])
                    if summary_re:
                        other_class = summary_re.group(1)
                        item_links[other_class] = item
                        full_match = summary_re.group(0)
                        if full_match == item['summary']:
                            skip_items[item['name']] = item['summary']


        for item in class_yaml['items']:
            if item['type'] in accepted_types:

                source_file = item['source']['path']
                out_file = convert_to_filename(main_out_file, source_file, split_format)
                if out_file not in out_files:
                    out_files[out_file] = []
                    table_files[out_file] = []
                    ref_links[out_file] = {}

                github_link = convert_to_link(source_file)
                ref_links[out_file][github_link] = True

                if item['name'] in skip_items:
                    continue
                if 'const ' in item['syntax']['content']:
                    continue
                if '[NonSerialized]' in item['syntax']['content']:
                    continue
                backup_item = None
                if item['name'] in item_links:
                    backup_item = item_links[item['name']]
                doc_txt, table_txt = convertToDocs(item, backup_item, friendly_name)
                out_files[out_file].append(doc_txt + "\n\n")
                if is_quick_reference:
                    table_files[out_file].append(table_txt + "\n")


    for out_file in out_files:
        outfile_full = os.path.join("..", "DataAsset", "WIKI", "Docs", out_file + ".txt")
        outfile_dir, _ = os.path.split(outfile_full)
        os.makedirs(outfile_dir, exist_ok=True)
        with open(outfile_full, 'w', encoding='utf-8') as txt:
            first_key = next(iter(classes))
            first_class = first_key.split('.')[-1]

            if is_quick_reference:
                txt.write("{{Hat Note|More functions: [[Script Reference]]''}}\n\n")

            txt.write("This page documents the {0} class for Lua scripting.\n\n".format(first_class))
            if is_singleton:
                txt.write("As a singleton class, it can be accessed from Lua with <code>{0}</code>.\n\n".format(friendly_name))
            else:
                txt.write("As an instanced class, it be accessed from Lua after assigning the instance to a variable, such as <code>{0}</code>\n\n".format(friendly_name))

            write_rows = out_files[out_file]
            for row in write_rows:
                txt.write(row)

            txt.write("== References ==\n\n")
            for link in ref_links[out_file]:
                txt.write(link + "\n\n")

            if is_quick_reference:
                txt.write("[[Category:Quick Reference]]")
            else:
                txt.write("[[Category:Data Class Documentation]]")

    for out_file in table_files:
        write_rows = table_files[out_file]
        if len(write_rows) == 0:
            continue
        outfile_full = os.path.join("..", "DataAsset", "WIKI", "Docs", out_file, "Table.txt")
        outfile_dir, _ = os.path.split(outfile_full)
        os.makedirs(outfile_dir, exist_ok=True)
        with open(outfile_full, 'w', encoding='utf-8') as txt:

            txt.write('<table class="wikitable">\n<tr>\n<th>Name</th>\n<th>Description</th>\n</tr>')
            for row in write_rows:
                txt.write(row)
            txt.write('</table>')

def main():

    class_maps = {
        "RogueEssence.Script.ScriptAI": "AI"
    }
    convertClassesToWiki("AI (functions)", "AI", True, True, class_maps, None, ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptDungeon": "DUNGEON"
    }
    convertClassesToWiki("Dungeon (functions)", "DUNGEON", True, True, class_maps, None, ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptGame": "GAME",
    }
    convertClassesToWiki("Game (functions)", "GAME", True, True, class_maps, "ScriptGame", ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptGround": "GROUND",
    }
    convertClassesToWiki("Ground (functions)", "GROUND", True, True, class_maps, "ScriptGround", ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptSound": "SOUND",
    }
    convertClassesToWiki("Sound (functions)", "SOUND", True, True, class_maps, None, ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptStrings": "STRINGS",
    }
    convertClassesToWiki("Strings (functions)", "STRINGS", True, True, class_maps, None, ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptTask": "TASK",
    }
    convertClassesToWiki("Task (functions)", "TASK", True, True, class_maps, None, ["Method", "Field"])

    class_maps = {
        "RogueEssence.Script.ScriptUI": "UI",
    }
    convertClassesToWiki("UI (functions)", "UI", True, True, class_maps, "ScriptUI", ["Method", "Field"])


    class_maps = {
        "RogueEssence.Dungeon.Character": "Character",
        "RogueEssence.Dungeon.CharData": "CharData"
    }
    convertClassesToWiki("Class%3ACharacter", "character", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Ground.GroundChar": "GroundChar",
        "RogueEssence.Ground.GroundAIUser": "GroundAIUser",
        "RogueEssence.Ground.BaseTaskUser": "BaseTaskUser",
        "RogueEssence.Ground.GroundEntity": "GroundEntity"
    }
    convertClassesToWiki("Class%3AGroundChar", "groundChar", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Dungeon.BattleContext": "BattleContext",
        "RogueEssence.Dungeon.UserTargetGameContext": "UserTargetGameContext",
        "RogueEssence.Dungeon.GameContext": "GameContext"
    }
    convertClassesToWiki("Class%3ABattleContext", "battleContext", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.BattleData": "BattleData"
    }
    convertClassesToWiki("Class%3ABattleData", "battleData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.TileData": "TileData"
    }
    convertClassesToWiki("Class%3ATileData", "tileData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.MapStatusData": "MapStatusData"
    }
    convertClassesToWiki("Class%3AMapStatusData", "mapStatusData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.StatusData": "StatusData"
    }
    convertClassesToWiki("Class%3AStatusData", "statusData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.SkillData": "SkillData"
    }
    convertClassesToWiki("Class%3ASkillData", "skillData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.IntrinsicData": "IntrinsicData"
    }
    convertClassesToWiki("Class%3AIntrinsicData", "intrisicData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.ItemData": "ItemData"
    }
    convertClassesToWiki("Class%3AItemData", "itemData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.MonsterData": "MonsterData"
    }
    convertClassesToWiki("Class%3AMonsterData", "monsterData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "PMDC.Data.MonsterFormData": "MonsterFormData",
        "RogueEssence.Data.BaseMonsterForm": "BaseMonsterForm"
    }
    convertClassesToWiki("Class%3AMonsterFormData", "monsterFormData", False, False, class_maps, None, ["Property", "Field"])

    class_maps = {
        "RogueEssence.Data.DataManager": "_DATA"
    }
    convertClassesToWiki("Class%3ADataManager", "_DATA", True, False, class_maps, None, ["Property", "Field", "Method"])

    print("Complete.")

if __name__ == '__main__':
    main()