import os
import time

from oauth2client import tools
import json
import requests
import re
from urllib.error import HTTPError

import argparse
flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()

APPLICATION_NAME = 'Wiki Sync'

class WikiGen:

    def __init__(self, credentials):
        self._credentials = credentials

    def request_with_retry(self, request):

        wait_sec = 2
        for i in range(6):
            response = request()
            if response.status_code == 403:
                pass
            elif response.status_code == 500:
                pass
            else:
                break
            print("{0} {1} returned {2}, retrying in {3}s".format(response.request.method, response.request.url, response.status_code, wait_sec))
            time.sleep(wait_sec)
            wait_sec *= 2

        return response

    def uploadPage(self, dir, file, page, mergeF):
        headers = {
            'User-Agent': 'MediaWiki REST API docs examples/0.1 (https://www.mediawiki.org/wiki/API_talk:REST_API)',
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + self._credentials
        }

        url = 'https://wiki.pmdo.pmdcollab.org/wiki/rest.php/v1/page/' + page
        response = self.request_with_retry(lambda: requests.get(url))
        if response.status_code == 404:
            last_version = 0
            last_content = ""
        elif response.status_code == 200:
            data = response.json()
            last_version = data['latest']['id']
            last_content = data['source']
        else:
            response.raise_for_status()

        with open(os.path.join(dir, file), 'r', encoding='utf-8') as f:
            content = f.read()

        content = mergeF(content, last_content)

        if content.strip() == last_content.strip():
            return

        json_dict = {}
        json_dict['source'] = content
        json_dict['comment'] = 'Autogenerated update'
        if last_version > 0:
            json_dict['latest'] = { 'id': last_version }

        print('writing {0}'.format(page))
        response = self.request_with_retry(lambda: requests.put(url, headers=headers, data=json.dumps(json_dict)))
        response.raise_for_status()
        time.sleep(0.5)

    def takeOurs(self, content, last_content):
        return content

    def mergeDesc(self, content, last_content):
        prev_desc_match = re.search(r'\|description=(.+?)\n}}', last_content)
        if prev_desc_match:
            prev_desc = prev_desc_match.group(1)
            if not prev_desc.startswith('[TMP]'):
                content = re.sub('description=.*?\n', 'description={0}\n'.format(prev_desc), content)
        return content

    def mergeDocNotes(self, content, last_content):

        # in last_content, get all matches to templates in the form of a dict mapping ids to ranges
        last_snippets = {}
        match_iter = re.finditer(r'\{\{\w+\n\|title=(\w+)\n[\s\S]+?}}', last_content)
        for match in match_iter:
            snip = match.group(0)
            start = match.start(0)
            end = match.end(0)
            title = match.group(1)
            idx = 0
            while (title, idx) in last_snippets:
                idx += 1
            last_snippets[(title, idx)] = (start, end)

        # in content, get all matches to templates in the form of a dict mapping ids to ranges
        current_snippets = {}
        match_iter = re.finditer(r'\{\{\w+\n\|title=(\w+)\n[\s\S]+?}}', content)
        for match in match_iter:
            start = match.start(0)
            end = match.end(0)
            title = match.group(1)
            idx = 0
            while (title, idx) in current_snippets:
                idx += 1
            current_snippets[(title, idx)] = (start, end)
        # ids are names, use order of finding for overrides
        replacements = []
        # for each current_snippets dict item, get the id, range, and snippet from content and last_content,
        for class_id in current_snippets:
            if class_id in last_snippets:
                last_range = last_snippets[class_id]
                last_snippet = last_content[last_range[0]:last_range[1]]
                cur_range = current_snippets[class_id]
                cur_snippet = content[cur_range[0]:cur_range[1]]
                # transfer notes to make new_snippet
                prev_desc_match = re.search(r'\|notes=(.+?)\n}}', last_snippet)
                if prev_desc_match:
                    prev_desc = prev_desc_match.group(1)
                    new_snippet = re.sub('notes=.*?\n', 'notes={0}\n'.format(prev_desc), cur_snippet)
                    # populate a list that contains range + new snippet
                    replacements.append((cur_range, new_snippet))
        # sort the ranges + snippets in reverse order of starting index
        replacements = sorted(replacements, reverse=True)
        for range, snippet in replacements:
            start = range[0]
            end = range[1]
            content = content[:start] + snippet + content[end:]

        return content

    def uploadDir(self, dir, child):
        self.uploadDirF(dir, child, self.takeOurs)

    def uploadDirF(self, dir, child, mergeF):
        for file in os.listdir(os.path.join(dir, child)):
            full_child = os.path.join(child, file)
            if os.path.isdir(os.path.join(dir, full_child)):
                self.uploadDirF(dir, full_child, mergeF)
            else:
                page_name, _ = os.path.splitext(full_child.replace('%3A', ':').replace('\\', '%2F').replace(' ', '_'))
                self.uploadPage(dir, full_child, page_name, mergeF)

def get_credentials():
    """Gets valid user credentials from storage.
    Returns:
        Credentials, the obtained credential.
    """
    credential_file = os.path.join('wiki_token.txt')
    with open(credential_file, 'r') as f:
        credentials = f.read()
    return credentials



def main():
    """
    Synchronizes data with the wiki
    """
    credentials = get_credentials()
    wikiGen = WikiGen(credentials)

    #wikiGen.uploadPage(os.path.join("..", "DataAsset", "Docs"), "BattleContext.txt", "Class:BattleContext")

    wikiGen.uploadDirF(os.path.join("..", "DataAsset", "WIKI", "Docs"), "", wikiGen.mergeDocNotes)
    wikiGen.uploadDirF(os.path.join("..", "DataAsset", "WIKI", "Data"), "", wikiGen.mergeDesc)

    print("Complete.")

if __name__ == '__main__':
    main()