import os
from oauth2client import tools
import json
import requests
import re
from urllib.error import HTTPError

import argparse
flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()

APPLICATION_NAME = 'Wiki Sync'

class WikiGen:

    def __init__(self, credentials):
        self._credentials = credentials

    def uploadPage(self, dir, file, page, mergeF):
        headers = {
            'User-Agent': 'MediaWiki REST API docs examples/0.1 (https://www.mediawiki.org/wiki/API_talk:REST_API)',
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + self._credentials
        }

        url = 'https://wiki.pmdo.pmdcollab.org/wiki/rest.php/v1/page/' + page
        response = requests.get(url)
        if response.status_code == 404:
            last_version = 0
            last_content = ""
        elif response.status_code == 200:
            data = response.json()
            last_version = data['latest']['id']
            last_content = data['source']
        else:
            raise Exception()
            #raise HTTPError(url, response.status_code, str(response.content), str(RETRIEVE_HEADERS), None)

        with open(os.path.join(dir, file), 'r', encoding='utf-8') as f:
            content = f.read()

        content = mergeF(content, last_content)

        if content.strip() == last_content.strip():
            return

        json_dict = {}
        json_dict['source'] = content
        json_dict['comment'] = 'Autogenerated update'
        if last_version > 0:
            json_dict['latest'] = { 'id': last_version }
        response = requests.put(url, headers=headers, data=json.dumps(json_dict))

        if response.status_code != 200 and response.status_code != 201:
            raise Exception()
            #raise HTTPError(url, response.status_code, str(response.content), str(RETRIEVE_HEADERS), None)

    def takeOurs(self, content, last_content):
        return content

    def mergeDesc(self, content, last_content):
        prev_desc_match = re.search(r'\|effects=(.+?)\n}}', last_content)
        if prev_desc_match:
            prev_desc = prev_desc_match.group(1)
            if not prev_desc.startswith('[TMP]'):
                content = re.sub('effects=.+?\n', 'effects={0}\n'.format(prev_desc), content)
        return content

    def uploadDir(self, dir, child):
        self.uploadDirF(dir, child, self.takeOurs)

    def uploadDirF(self, dir, child, mergeF):
        for file in os.listdir(os.path.join(dir, child)):
            full_child = os.path.join(child, file)
            if os.path.isdir(os.path.join(dir, full_child)):
                self.uploadDirF(dir, full_child, mergeF)
            else:
                page_name, _ = os.path.splitext(full_child.replace('%3A', ':').replace('\\', '%2F').replace(' ', '_'))
                self.uploadPage(dir, full_child, page_name, mergeF)

def get_credentials():
    """Gets valid user credentials from storage.
    Returns:
        Credentials, the obtained credential.
    """
    credential_file = os.path.join('wiki_token.txt')
    with open(credential_file, 'r') as f:
        credentials = f.read()
    return credentials



def main():
    """
    Synchronizes data with the wiki
    """
    credentials = get_credentials()
    wikiGen = WikiGen(credentials)

    #wikiGen.uploadPage(os.path.join("..", "DataAsset", "Docs"), "BattleContext.txt", "Class:BattleContext")

    wikiGen.uploadDir(os.path.join("..", "DataAsset", "WIKI"), "")
    #wikiGen.uploadDirF(os.path.join("..", "DataAsset", "WIKI"), "", wikiGen.mergeDesc)

    print("Complete.")

if __name__ == '__main__':
    main()